version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network
    depends_on:
      - php

  db:
    image: postgres
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bowling_club
      POSTGRES_USER: admin
    volumes:
      - ./app/database:/app/database
    networks:
      - pg-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - pg-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    networks:
      - pg-network
    depends_on:
      - db

  pgadmin-wdpai:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data: